name: Build Kivy Android App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    env:
      PROJECT_DIR: ${{ github.workspace }}
      BUILD_DIR: ${{ github.workspace }}/bin

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install kivy pyjnius cryptography plyer buildozer

      - name: Ensure assets folder exists
        run: |
          mkdir -p assets
          if [ -d assets_source ]; then
            cp -r assets_source/* assets/
          fi

      - name: Create output folder
        run: mkdir -p bin

      - name: Build APK (debug)
        run: buildozer android debug deploy run

      - name: Build APK (release)
        run: buildozer android release

      - name: List APK output
        run: ls -lh bin/