name: Build Kivy Android App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    env:
      PROJECT_DIR: ${{ github.workspace }}
      BUILD_DIR: ${{ github.workspace }}/bin
      ANDROID_HOME: $HOME/android-sdk
      ANDROID_SDK_ROOT: $HOME/android-sdk
      ANDROID_NDK_HOME: $HOME/android-sdk/ndk/25.2.9519653
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
      PATH: $HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$JAVA_HOME/bin:$PATH

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install essential system tools
        run: |
          sudo apt-get update
          sudo apt-get install -y tar unzip wget git openjdk-11-jdk python3-pip build-essential

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Upgrade pip and install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install kivy pyjnius cryptography plyer buildozer cython

      - name: Install Android SDK, NDK, and platform-tools
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip
          mv cmdline-tools cmdline-tools-latest
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "platforms;android-33" "ndk;25.2.9519653"

      - name: Ensure assets folder exists
        run: |
          mkdir -p assets
          if [ -d assets_source ]; then
            cp -r assets_source/* assets/
          fi

      - name: Create output folder
        run: mkdir -p bin

      - name: Build APK (debug)
        run: buildozer android debug deploy run

      - name: Build APK (release)
        run: buildozer android release

      - name: List APK output
        run: ls -lh bin/