name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk

    steps:
      # 1. Checkout du code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Installer Java (nécessaire pour Gradle)
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 3. Installer SDK Android
      - name: Install Android SDK
        run: |
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          cd $ANDROID_SDK_ROOT/cmdline-tools
          curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-9123335_latest.zip
          unzip commandlinetools.zip
          rm commandlinetools.zip
          mkdir -p latest
          mv cmdline-tools/* latest/
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      # 4. Rendre gradlew exécutable
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # 5. Étape de débogage : vérifier fichiers
      - name: List workspace files
        run: ls -la

      # 6. Build APK
      - name: Build with Gradle
        run: ./gradlew assembleDebug
